### PR TITLE
Update to 13.0.2

### LINKED ISSUE #16: Requested Rebuild at Dockerhub?
We're up to 13.0.2. Could you do a rebuild for us?

Thanks!

### PR DESCRIPTION
**Pull request by benyanke**
Resolved #16

### CODE REVIEW

**Comment by frebib** [comment]
Duplicate to https://github.com/Wonderfall/docker-nextcloud/pull/15

**Comment by benyanke** [comment]
Thanks, forgot to check first.

**Comment by rgarcia89** [comment]
@benyanke I cant see the commit in the commit history of wonderfall/docker-nextcloud also the docker hub image has not been updated so far. When is this going to happy? Am I mssing something?

**Comment by frebib** [comment]
@rgarcia89 From the README:
> Any contribution is welcome, but please be aware I'm very busy currently.

I guess it'll happen when Wonderfall finds some time

**Comment by rgarcia89** [comment]
If you let me know how I can do this. However, I will surely not be able to push the image to the wonderfall hub or?

**Comment by frebib** [comment]
The only thing we can do is wait patiently

**Comment by benyanke** [comment]
If I have a chance today, I'll pull out my repo again so we can upgrade for the time being. I'll build it on my own account so that you can upgrade by switching `wonderfall/nextcloud` for `benyanke/nextcloud` until he upgrades.

**Comment by benyanke** [comment]
See here: https://github.com/Wonderfall/docker-nextcloud/pull/15#issuecomment-386493304

@frebib @rgarcia89

**Pull request closed without merging**
