### PR TITLE
Version Bump

### PR DESCRIPTION
**Pull request by rushsteve1**
13.0.1 to 13.0.2
Since this is just a patch version it should be as simple as bumping the number.

### CODE REVIEW

**Comment by rushsteve1** [comment]
@Wonderfall Sorry to ping you but this has just sat for a few days now and is somewhat important.

**Comment by benyanke** [comment]
https://hub.docker.com/r/benyanke/nextcloud is now set up.

The docker build is still running, but `benyanke/nextcloud:13` should be up there shortly.

**Comment by rushsteve1** [comment]
Thank you @benyanke I have personally switched to your branch for now and would advise others to do the same. I will leave this PR open on the off chance @wonderfall returns, and as a warning to future visitors.

**Comment by benyanke** [comment]
Sounds good - Thanks steve.

While I may get busy (as we all do), I know I can commit, without a doubt, to at least responding and merging fully-ready PRs, so we don't get stuck here again.

**Comment by Wonderfall** [comment]
Sorry the delay. Had some important things to deal with lately.
I appreciate @benyanke's initiative, the spirit of my project is to provide inspiration, not guaranteed maintenance and up-to-date images. As you all know now I'm not a good maintainer. If somehow I no longer maintain this repo, you should know how to build yourself!

**Comment by benyanke** [comment]
Absolutely - thank you for the excellent foundation as well. Some well designed Dockerfile and init scripts!

**Pull request closed without merging**
